_BASE_: "Base-SparseInst.yaml"
MODEL:
  WEIGHTS: "/home/aboggaram/models/sparse_inst_r50_giam_aug_2b7d68.pth"
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.00005
  STEPS: (5000, 7500, 15000, 25000)
  MAX_ITER: 36000
  WEIGHT_DECAY: 0.05
  OPTIMIZER: "ADAMW"
  AMP:
    ENABLED: True
INPUT:
  MIN_SIZE_TRAIN: (416, 448, 480, 512, 544, 576, 608, 640)
  MAX_SIZE_TRAIN: 1024
  MIN_SIZE_TEST: 640
  MAX_SIZE_TEST: 1024
  FORMAT: "RGB"
  MASK_FORMAT: "polygon"
  CROP:
    ENABLED: True
    TYPE: "absolute_range"
    SIZE: (512, 800)
OUTPUT_DIR: "/home/aboggaram/models/octiva_sparse_inst_r50_giam_fp16_10_26"
