_BASE_: "Base-SparseInst.yaml"
MODEL:
  WEIGHTS: "/home/aboggaram/models/sparse_inst_r50_giam_aug_2b7d68.pth"
SOLVER:
  AMP:
    ENABLED: True
OUTPUT_DIR: "/home/aboggaram/models/octiva_sparse_inst_r50_giam_fp16"